apply plugin: 'com.android.application'

android {
    compileSdkVersion 36

    defaultConfig {
        applicationId "org.phramusca.jamuz"
        minSdkVersion 21
        targetSdkVersion 36
        versionName "0.6.11"
        versionCode 18
    }
    buildTypes {
        debug {
            applicationIdSuffix ".debug"
            versionNameSuffix "-debug"
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        targetCompatibility JavaVersion.VERSION_21
        sourceCompatibility JavaVersion.VERSION_21
    }
    namespace 'phramusca.com.jamuzremote'
    lint {
        baseline file('lint-baseline.xml')
    }

}

dependencies {
    testImplementation 'junit:junit:4.13.2'
    implementation 'net.jthink:jaudiotagger:3.0.1'
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'com.google.android.flexbox:flexbox:3.0.0'
    implementation 'org.ocpsoft.prettytime:prettytime:4.0.3.Final'
    implementation("androidx.media:media:1.7.1")

    implementation 'com.google.code.gson:gson:2.13.2'
    implementation 'com.google.guava:guava:33.5.0-android'

    //OK Http
    // DO NOT UPDATE okhttp more than 4.9.3 or update okhttp-eventsource before
    implementation 'com.squareup.okhttp3:okhttp:4.9.3'
    // DO NOT UPDATE okhttp-eventsource more than 3.0.0 or raise minSdkVersion to 26+
    implementation 'com.launchdarkly:okhttp-eventsource:3.0.0'

    //QR Code
    // DO NOT UPDATE zxing-android-embedded more than 3.6.0 or update minSdkVersion accordingly
    // Moreover, with 4.3.0, MediaButtonReceiver is not found.
    //      Looks like some changes are required with 4.3.0: https://github.com/journeyapps/zxing-android-embedded/releases/tag/v4.3.0
    implementation 'com.journeyapps:zxing-android-embedded:3.6.0'
    // DO NOT UPDATE zxing:core more than 3.3.3 or set minSdkVersion >= 24
    // https://github.com/zxing/zxing/issues/1170
    implementation 'com.google.zxing:core:3.3.3'
}

repositories {
    mavenCentral()
}