name: Build & Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Releasing using Hub
      uses: ShowMeThe/github_action_release@v0.01
      env:
       GITHUB_TOKEN: ${{ secrets.TOKEN }}
