name: Build & Publish Debug APK

on:
  workflow_dispatch:
    branches: [ master ]
  # push:
    # branches: [ master ]
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
#   pull_request:
#     branches: [ master ]

jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:

    - name: "Checkout"
      uses: actions/checkout@v3

    - name: "Setup JDK 11"
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: "Grant execute permission for gradlew"
      run: chmod +x gradlew

    - name: "Build release apk with Gradle"
      run: ./gradlew clean assembleRelease

    - name: "Sign release apk"
      uses: ilharp/sign-android-release@v1 # Or use @nightly
      id: sign_app
      with:
        releaseDir: app/build/outputs/apk/release
        signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
        keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
        keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
        buildToolsVersion: 33.0.0

    # Upload your signed file if you want
    # - uses: actions/upload-artifact@v2
    #   with:
    #     name: Signed app bundle
    #     path: ${{steps.sign_app.outputs.signedFile}}

    - name: Set asset_name
      id: vars
      run: echo ::set-output name=asset_name::JaMuz_Remote_${GITHUB_REF_NAME}.apk

    # - name: Bump version
    #   uses: chkfung/android-version-actions@v1.2.1
    #   with:
    #     gradlePath: app/build.gradle
    #     versionCode: ${{GITHUB_RUN_NUMBER}}
    #     versionName: 1.0.0

    - name: Get Apk Info
      id: apk
      uses: JantHsueh/get-apk-version-action@master
      with:
      apkPath: ${{steps.sign_app.outputs.signedFile}}

    - name: "Read file contents"
      id: read_file
      uses: andstor/file-reader-action@v1
      with:
        path: "metadata/en/changelogs/${steps.apk.outputs.versionCode}.txt"

    - name: File contents
      run: echo "${ steps.read_file.outputs.contents }"

    # - name: Read VERSION file
    #   id: getversion
    #   run: echo "::set-output name=version::$(cat VERSION)"

    - name: "Create release on github with apk"
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.TOKEN }}
        file: ${{steps.sign_app.outputs.signedFile}}
        asset_name: ${{ steps.vars.outputs.asset_name }}
        tag: ${{ github.ref }}
        overwrite: true
        body: ${{ steps.read_file.outputs.contents }}
